services:
  actual-server:
    image: actualbudget/actual-server:latest
    container_name: actual_server
    restart: unless-stopped
    ports:
      - '5006:5006'
    volumes:
      - ./actual-data:/data
      - ./actual_server/config.json:/data/config.json
      - ./actual_server/localhost.key:/data/budget.suarzac.com.key
      - ./actual_server/localhost.crt:/data/budget.suarzac.com.crt
